name: care_link
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  animated_text_kit: ^4.2.3
  fl_chart: ^1.1.1
  flutter_feather_icons: ^2.0.0+1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  google_sign_in: ^6.3.0
  connectivity_plus: ^7.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.9.0

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/flash-icon.png"
    adaptive_icon_foreground: "assets/images/flash-icon.png"
    adaptive_icon_background: "#ffffff"

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: JustMeAgainDownHere
      fonts:
        - asset: assets/fonts/Just_Me_Again_Down_Here/JustMeAgainDownHere-Regular.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: Assets